apiVersion: '2021-07-01'
location: 'westeurope'
properties:
  imageRegistryCredentials:
  - server: laraconseil.azurecr.io
    username: laraconseil
    password: PbM1wqxfcHp4tSzOoAXCWBba0agZcEcCPAwF7dsJdr+ACRDpppkP
  subnetIds:
  - id: "/subscriptions/97761089-aedd-48cc-82a4-868666d706eb/resourceGroups/resgp-lc/providers/Microsoft.Network/virtualNetworks/laraconseil-vnet/subnets/laraconseil-subnet"
  ipAddress:
    type: 'Private'
    ports:
    - protocol: 'TCP'
      port: 443
    - protocol: 'TCP'
      port: 80
    - protocol: 'TCP'
      port: 1433
    - protocol: 'TCP'
      port: 8080
    - protocol: 'TCP'
      port: 5130
    - protocol: 'TCP'
      port: 5003
    - protocol: 'TCP'
      port: 5004
    - protocol: 'TCP'
      port: 8500
  containers:
  - name: sqlserver
    properties:
      image: laraconseil.azurecr.io/mssql-server:2019-latest
      ports:
      - port: 1433
      environmentVariables:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "StrongPassword@123"
      resources:
        requests:
          cpu: 0.75
          memoryInGB: 1.5
      volumeMounts:
      - name: sql-data
        mountPath: /var/opt/mssql
  - name: keycloak
    properties:
      image: laraconseil.azurecr.io/keycloak:20.0.3
      ports:
      - port: 8080
      environmentVariables:
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: admin
      command:
      - "/opt/keycloak/bin/kc.sh"
      - "start-dev"
      resources:
        requests:
          cpu: 0.75
          memoryInGB: 2
  - name: consul
    properties:
      image: laraconseil.azurecr.io/consul:1.14.6
      ports:
      - port: 8500
      - port: 8600
      resources:
        requests:
          cpu: 0.25
          memoryInGB: 0.5
  - name: apigateway
    properties:
      image: laraconseil.azurecr.io/apigateway
      ports:
      - port: 5130
      - port: 7277
      environmentVariables:
      - name: CONSUL_HTTP_ADDR
        value: "http://consul:8500"
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 1
  - name: growerservice
    properties:
      image: laraconseil.azurecr.io/growerservice
      ports:
      - port: 5003
      environmentVariables:
      - name: CONSUL_HTTP_ADDR
        value: "http://consul:8500"
      - name: SERVICE_NAME
        value: "grower-service"
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 1
  - name: stationservice
    properties:
      image: laraconseil.azurecr.io/stationservice
      ports:
      - port: 5004
      environmentVariables:
      - name: CONSUL_HTTP_ADDR
        value: "http://consul:8500"
      - name: SERVICE_NAME
        value: "station-service"
      resources:
        requests:
          cpu: 0.5
          memoryInGB: 1
  - name: reverse-proxy
    properties:
      image: laraconseil.azurecr.io/nginx:latest
      ports:
      - port: 443
      - port: 80
      volumeMounts:
      - name: ssl-cert
        mountPath: /etc/nginx/ssl
      resources:
        requests:
          cpu: 0.25
          memoryInGB: 0.5
  osType: 'Linux'
  volumes:
  - name: sql-data
    azureFile:
      shareName: sqlshare
      storageAccountName: laraconseilstorage
      storageAccountKey: g0arcFUjipSX8T1dZskqfn+jtz9JLuvAvb/NROGJG2fv8ozwpPmNnbsXodXpXVT/ZxhLsciBfWUA+AStvEhtbw==
  - name: ssl-cert
    azureFile:
      shareName: sslshare
      storageAccountName: laraconseilstorage
      storageAccountKey: g0arcFUjipSX8T1dZskqfn+jtz9JLuvAvb/NROGJG2fv8ozwpPmNnbsXodXpXVT/ZxhLsciBfWUA+AStvEhtbw==
