services:
  # Keycloak for authentication and authorization
  keycloak:
    image: lcrgacr.azurecr.io/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - our-network

  # API Gateway
  apigateway:
    image: lcrgacr.azurecr.io/apigateway:latest
    container_name: apigateway
    ports:
      - "5130:5130"
    depends_on:
      - grower-service
      - station-service
      - messager-service
    environment:
      SERVICE_NAME: apigateway-service
      SERVICE_HOST: apigateway-service
      SERVICE_PORT: 5130
      ASPNETCORE_ENVIRONMENT: Production
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      AllowedHosts: "*"
    networks:
      - our-network

  # Grower Service
  grower-service:
    image: lcrgacr.azurecr.io/grower-service:latest
    container_name: grower-service
    ports:
      - "5003:5003"
    environment:
      SERVICE_NAME: grower-service
      SERVICE_HOST: grower-service
      SERVICE_PORT: 5003
      ASPNETCORE_ENVIRONMENT: Production
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      AllowedHosts: "*"
    networks:
      - our-network

  # Station Service
  station-service:
    image: lcrgacr.azurecr.io/station-service:latest
    container_name: station-service
    ports:
      - "5004:5004"
    environment:
      SERVICE_NAME: station-service
      SERVICE_HOST: station-service
      SERVICE_PORT: 5004
      ASPNETCORE_ENVIRONMENT: Production
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      AllowedHosts: "*"
    networks:
      - our-network

  # MultiTenant Stripe API
  multitenant-api:
    image: lcrgacr.azurecr.io/multitenant-api:latest
    container_name: multitenant-api
    ports:
      - "5005:5005"
    environment:
      SERVICE_NAME: multitenant-api
      SERVICE_HOST: multitenant-api
      SERVICE_PORT: 5005
      ASPNETCORE_ENVIRONMENT: Production
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      AllowedHosts: "*"
      Stripe__SecretKey: "your_stripe_secret_key"
      Stripe__PublishableKey: "your_stripe_publishable_key"
      Stripe__WebhookSecret: "your_stripe_webhook_secret"
    depends_on:
      - keycloak
    networks:
      - our-network

  # Messager Service
  messager-service:
    image: lcrgacr.azurecr.io/messager-service:latest
    container_name: messager-service
    ports:
      - "5006:5006"
    environment:
      SERVICE_NAME: messager-service
      SERVICE_HOST: messager-service
      SERVICE_PORT: 5006
      ASPNETCORE_ENVIRONMENT: Production
      Logging__LogLevel__Default: "Information"
      Logging__LogLevel__Microsoft.AspNetCore: "Warning"
      AllowedHosts: "*"
      Azure__ConnectionString: "your_azure_connection_string"
      Azure__SenderEmail: "your_sender_email"
    networks:
      - our-network

  # Angular Frontend
  subscription-app:
    image: lcrgacr.azurecr.io/subscription-app:latest
    container_name: subscription-app
    ports:
      - "4200:80"
    networks:
      - our-network

networks:
  our-network:
    driver: bridge
