services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5130:5130"
      - "7277:7277"

  grower-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:5003" # HTTP

  station-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:5004" # HTTP
