services:
  keycloak:
    image: lcrgacr.azurecr.io/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    networks:
      - our-network

  consul:
    image: lcrgacr.azurecr.io/consul:latest
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -dev -client=0.0.0.0
    networks:
      - our-network

  apigateway:
    image: lcrgacr.azurecr.io/apigateway:latest
    container_name: apigateway
    ports:
      - "5130:5130"
    depends_on:
      - consul
      - grower-service
      - station-service
    environment:
      CONSUL_HTTP_ADDR: "http://consul:8500"
      SERVICE_NAME: apigateway-service
      SERVICE_HOST: apigateway-service
      SERVICE_PORT: 5130
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - our-network

  grower-service:
    image: lcrgacr.azurecr.io/grower-service:latest
    container_name: grower-service
    ports:
      - "5003:5003"
    environment:
      CONSUL_HTTP_ADDR: "http://consul:8500"
      SERVICE_NAME: grower-service
      SERVICE_HOST: grower-service
      SERVICE_PORT: 5003
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - consul
    networks:
      - our-network

  station-service:
    image: lcrgacr.azurecr.io/station-service:latest
    container_name: station-service
    ports:
      - "5004:5004"
    environment:
      CONSUL_HTTP_ADDR: "http://consul:8500"
      SERVICE_NAME: station-service
      SERVICE_HOST: station-service
      SERVICE_PORT: 5004
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - consul
    networks:
      - our-network

  multitenant-api:
    image: lcrgacr.azurecr.io/multitenant-api:latest
    container_name: multitenant-api
    ports:
      - "5005:5005"
    environment:
      CONSUL_HTTP_ADDR: "http://consul:8500"
      SERVICE_NAME: multitenant-api
      SERVICE_HOST: multitenant-api
      SERVICE_PORT: 5005
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - our-network

  subscription-app:
    image: lcrgacr.azurecr.io/subscription-app:latest
    container_name: subscription-app
    ports:
      - "4200:80"
    networks:
      - our-network

networks:
  our-network:
    driver: bridge
