name: Build, Push, and Deploy Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Azure Container Registry (ACR)
      - name: Log in to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login lcrgacr.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # Step 3: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Run the Build and Deploy Script
      - name: Build and Push Docker Images
        run: |
          chmod +x deploys/build-and-deploy.sh
          ./deploys/build-and-deploy.sh
          
      # Step 5: Manage Azure Container Apps
      - name: Update, Stop, and Start Azure Container Apps
        run: |
          chmod +x deploys/manage-containerapps.sh
          ./deploys/manage-containerapps.sh
